### ISSUE TITLE
Manage index creation

### ISSUE THREAD

**Issue by ezyang** [yesodweb/persistent#109]
By default, persistent generates no indexes. persistent should permit index suggestions in the model, attempt to create them, and give warnings when it is not possible to create an index in the current backend.

Original: https://github.com/yesodweb/yesod/issues/444#issuecomment-11766160

Related: http://stackoverflow.com/questions/11861339/sql-indices-with-database-persist-yesod-web-framework

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by RasmusKlett** [comment]
I think this is still very relevant. With it, I would be able to handle all my SQL needs from Persistent.
Additionally, maybe Django's approach of adding indexes to [foreign key](https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey) fields by default? 
In [this issue](https://github.com/yesodweb/yesod/issues/444) it is mentioned that maybe a manual alternative should simply be documented instead, has that been done? That would be a reasonable alternative, but I cannot find it anywhere.

**Comment by gregwebs** [comment]
Automatically handling indexes is fraught with peril. When data gets large, index creation can take an extremely long time. Generally it is best to get some advise from persistent about how to do migrations but manage them yourself. You can try sqitch, dbmigrations, or even ActiveRecord migrations. Let us know what works for you.

**Comment by RasmusKlett** [comment]
In the Django world where I come from, it seems to work very well, and I really don't see why it wouldn't here. People with very big data can just not use the feature, and for the rest of us it would be very nice.
But anyway, if manually managed migrations are recommended, maybe it should be documented somwhere easily findable? Everyone with medium-sized data is bound to have this issue.

**Comment by gregwebs** [comment]
Where else should this be documented?

**Comment by RasmusKlett** [comment]
I was imagining something like a github wiki page showing how to get a basic setup running. Or it might even be in the Yesod book?

**Comment by cies** [comment]
> With it, I would be able to handle all my SQL needs from Persistent

For me not all needs (I certainly need Esqueleto and some just-drop-down-to-SQL-here'n'there), but it would allow me to do all migrations from Haskell.  I also would prefer to see them in the TH DSL, then in some `.sql` file that need to be executed "every once in a while" (I dont know if dbs skip the action "superfluously creating  already existing indexes" gracefully -- if so that would make keeping indexes in raw SQL quite a bit more annoying when deploying to different targets).

**Comment by rdnetto** [comment]
Speaking as someone new to Persistent (who found this issue when trying to figure out how to handle index creation), the thing I'd like to see most is the best practice (whatever that is) for index creation documented in the [Yesod book](http://www.yesodweb.com/book/persistent). The alternative is that everyone has to re-discover this for themselves, and repeat the same mistakes.

**Comment by sboosali** [comment]
This limitation is reasonable needs to be documented, probably in runMigration. Also, by "persistent advising you", do you mean to just print out showMigration and add indices manually?

**Comment by gregwebs** [comment]
Yeah, print out persistent's migrations. You can also generate SQL names from persistent for indexes, we could actually have functions around generating this SQL. Still I would want to leave running actual migrations in the hands of the user. And I would like to use existing migration frameworks rather than re-invent this wheel. Here are ones you could try:

## FlywayDB
Every feature you want, especially on the JVM
https://flywaydb.org/documentation/migration/sql
can use a CLI also, including docker image: https://github.com/shouldbee/docker-flyway

## Go CLI
sql-migrate: https://github.com/rubenv/sql-migrate
supports many DBs
no Env variable expansion!

rambler: https://github.com/elwinar/rambler
mysql/postgres/sqlite

## Sqitch (Perl)
sqitch: http://sqitch.org/
just runs the db client (e.g. psql)
has a nice story for versioning, etc

## LiquidBase
http://www.liquibase.org/index.html

**Comment by tysonzero** [comment]
Is there any chance that the ability to add indexes in the TH DSL will be considered? This is probably the biggest remaining issue I am having with persistent at the moment, a missing index is basically a correctness issue for the data I am dealing with, as the queries I want to run just will not ever finish without those indices present.

I can see how people dealing with complex migrations might perhaps want to go beyond running the auto generated migrations. However for my (and I'm sure many other people's) use case, complex migrations of existing data is not an issue, I just need to be able to rely on those indices being there even if I drop and rebuild the table.

There already exists infrastructure for creating `Unique` constraints, which actually in postgresql/sqlite automatically creates an index under the covers, so it seems to me as though the code for regular old indexes should not be any harder or more backend specific than `Unique` constraint are, but I could be wrong.

**Comment by MaxGabriel** [comment]
Personally I am in favor of Persistent handling indexes. MySQL and Postgres now support online index creation, so queries aren’t blocked anymore, unless you have an exceptionally large table (like, multi-day index creation times)

So I would welcome a PR for this

**Comment by tysonzero** [comment]
@MaxGabriel That's good to know, thanks! I unfortunately do not know Template Haskell yet and do not have any free time at the moment, so it will be quite some time before I can make such a PR, if anyone else wants to make it please go ahead.

**Comment by googleson78** [comment]
This is also discussed at #919
