### ISSUE TITLE
2.13 support for mongodb

### ISSUE THREAD

**Issue by aschmois** [yesodweb/persistent#1284]
I noticed mongodb to be broken in 2.13 and saw the hiatus note on the library. I'm curious to know what specifically is broken and trying to acertain the level of effort required to fix it. Our team is willing to work on it contingent of level of effort. Any thoughts on it will help!

**Comment by parsonsmatt** [comment]
The problem was all in the `EmbedEntityDef`, and the relevant cycle breaking code. Simplifying that resulted in a massive speedup in compilation time and a much better code structure.

It's used a ton for MongoDB, and the recursive nature of the old structure is necessary because the Mongo backend uses it everywhere. But it's actually subtly broken for a lot of uses, so instead of "fixing" it (and breaking existing users), I decided to just pause support until a user of the library was willing to step forward.

I'd be happy to accept additional maintainers that would be willing to get it working again. MongoDB is sufficiently different from the SQL backends, and I don't use it at all, that I don't feel great supporting it moving forward. But I'd be happy to advise on getting it working again!

**Comment by aschmois** [comment]
Went deep diving into the 2.13 pr merge and found https://github.com/yesodweb/persistent/pull/1256. I'll begin work on investigating what went wrong and seeing if I can make sense of the implementation. Thanks.

**Comment by aschmois** [comment]
Merged, uploaded, and released! https://hackage.haskell.org/package/persistent-mongoDB-2.13.0.0
