### ISSUE TITLE
Model TH support of type parameters

### ISSUE THREAD

**Issue by tim2CF** [yesodweb/persistent#1339]
I was not able to find in documentation what is the best true canonical way to define Persistent model which do accept type/kind parameters. For example, I need something like `data User (a :: Role) b = ...` where `a` and `b` might be used as phantom parameters of the User fields. With standard tools like `mkPersist` and similar I was able to define just simple `data User = ...`. Phantom type/kind parameters are very useful for type-safe but generic code (because runtime representation is still the same). It would be super cool to have parametrized Persistent models. This issue is follow-up for previous https://github.com/yesodweb/persistent/issues/1166 which has been already implemented, thanks a lot!

**Comment by parsonsmatt** [comment]
This is unsupported at the database level. The easiest way to solve this problem is to write a layer on top of `persistent` that solves this for you.

eg:

```haskell
module DB.User where

mkPersist sqlSettings [persistLowerCase|

User
    name String
    role Role

|]

module Domain.User where

import qualified DB.User as DB

data User (a :: Role) = User
  { name :: Name
  } 

fromDB :: DB.User -> Either (User 'Admin) (User 'Normal)
fromDB DB.User { .. } = 
  case userRole of
    Admin -> Left (User @'Admin { name = userName })
    Normal -> Right (User @'Normal { name = userName})
```

The `PersistEntity` class currently requires something of kind `*`. Making it poly-kinded would be possible, but introduce complexity.

To illustrate some of the complexity, consider a simplified class:

```haskell
class FromPersistRow a where
    fromPersistRow :: [PersistValue] -> Either Text a
```

For a simple `User`, it's relatively easy:

```haskell
instance FromPersistRow User where
    fromPersistRow [PersistText name, PersistText roleText] = do
        role <- fromPersistValue roleText
        pure User { userName = name, userRole = role }
```

But, the code we would need to generate for a `Role` is more complicated. We cannot provide simply `instance FromPersistRow User`, because `User` now has kind `Role -> Type`. We must provide an instance for each type of kind `Role`.

```haskell
instance FromPersistRow (User 'Admin) where
    fromPersistRow [PersistText name, PersistText roleText] = do
        role <- fromPersistValue roleText
        case role of
            Admin -> 
                pure User { userName = name, userRole = role }
            Normal ->
                Left "Expected an Admin, got Normal"

-- repeat for (User 'Normal)
```

You can simplify here with a `singleton` class.

```haskell
data Role = Normal | Admin
  deriving Eq

data SRole (a :: Role) where
    SNormal :: SRole 'Normal
    SAdmin :: SRole 'Admin

class KnownRole (a :: Role) where
    roleVal :: Proxy a -> Role

instance KnownRole 'Admin where
    roleVal _ = Admin

instance KnownRole 'Normal where
    roleVal _ = Normal

reifyRole :: Role -> (forall a. SRole a -> r) -> r
reifyRole role k = case role of
  Normal -> k SNormal
  Admin -> k SAdmin

instance (KnownRole role) => FromPersistRow (User role) where
    fromPersistRow [PersistText name, roleTxt] = do
        roleParsed <- fromPersistValue roleTxt
        if roleParsed == roleVal (Proxy @role)
            then pure User { userName = name }
            else Left "Unexpected role from database for what we're trying to parse"
```

That's all well and good, but now you need to figure out some way to specify how the database table is supposed to pick the right value. What if the `role` depends on a presence/absence of a record in another table - suppose a `UserAdmin` table.

So, ultimately, this ends up being quite a complicated feature to support. Furthermore, `persistent` types are supposed to represent *the database* and actions that you would perform *on the database*. They are not meant to be general-purpose domain types, suitable for use throughout your application.

**Comment by tim2CF** [comment]
Thanks for reply, @parsonsmatt !
Yes, dependency of type parameter on database row data is complex, I think I'll close this issue at least for now.
