### ISSUE TITLE
Give us more control over foreign key creation

### ISSUE THREAD

**Issue by pikajude** [yesodweb/persistent#141]
For example, given this relation:

```
Entry
  title Text

Tag
  name Text
  UniqueName name

EntryTag
  entryId EntryId
  tagId TagId
  UniqueEntryTag entryId tagId
```

I would specify that EntryTag is `ON CASCADE DELETE` so I can just kill a tag with a certain name and all the associated EntryTag models will be deleted (same if I want to delete an entry). Right now I have to load all the tag IDs into memory and use a DELETE ... WHERE ... IN

**Comment by BartAdv** [comment]
Sorry for digging up the old issue, but relates directly to my question - what is the rationale behind this? Why not just let programmer specify the additional options for a foreign key and not to have to care about calling `mkDeleteCascade` and then not to have use `deleteCascade` instead of `delete`?
