### ISSUE TITLE
getByValue doesn't work if Primary defined, and no Unique

### ISSUE THREAD

**Issue by vlatkoB** [yesodweb/persistent#309]
Hi,

I tried to use different type of primary key, but `getByValue` does not work.

``` haskell
TestDb
  aKey     Text
  aValue   Text
  Primary  aKey
  deriving Show Eq

tst = do
  insertBy rec
  getByValue rec -- Nothing
  where  rec = TestDb {testDbAKey = "123", testDbAValue = "Haskell"}
```

If `Primary aKey` is replaced with `UniqueTest aKey`, default id is used and all works as expected.

Shouldn't `Primary` be treated as `Unique`?
Or is this not the way to use it?

persistent-2.0.5

Best regards,

vlatko

**Comment by parsonsmatt** [comment]
I'm running into this as well. This is really unexpected behavior.

**Comment by 2piix** [comment]
I'm running into a similar situation, so I'm trying to think through it and maybe post my notes here.

I have a `Person` record with fields like `firstName` and `lastName`.  None of these are supposed to be unique, even in combination.  (How many John Smiths are there in the world?)  So the only unique constraint I have for this type of record is its primary key (which I am letting persistent define implicitly).

So I guess the problem is that the type of record doesn't even have a composite key.  The primary key could work as a uniqueness constraint, but that doesn't even get passed in (directly) because of the Entity abstractions.

Ideally I'd like a "do it all" method to do my insert or update instead of having to check (client-side) if my JSON value for a person has an id field.

I guess I'll do it client-side.

**Comment by gregwebs** [comment]
Probably not understanding, but seems like `upsert` would work for you?

**Comment by 2piix** [comment]
My understanding is that `upsert` requires a uniqueness constraint of the form `UniquePerson firstName lastName etc`.  But how many people named John Smith are there in the world?  I am hesitant to encode an arbitrary uniqueness constraint when even the combinations are not guaranteed to be unique.

So here's my use case:  building an Yesod site with a Knockout front-end.  To make a new `Person` through the front-end, I have to initialize a JavaScript representation of the `Person`.  As a matter of fact, the JavaScript includes an `id` field, so I could parse to an `Entity Person` IF the `id` field is not `null`.

In short, I am running into a slight impedance mismatch between the JSON and the Entity.  I am using the existence of a Key as my check on whether the value came from the database or not.  And I am wishing that `Entity` was defined as

    data Entity val = Entity { entityKey :: Maybe (Key val)
                             , entityVal :: val
                             }

so that I could have just function to do the logic of `repsert`ing without having to pass in a key.  (Because sometimes I don't know what the key will be at object initialization-time on the client)

I dunno, I don't expect you to make big changes to `Entity`.  I'm just thinking through my problem and this is where I landed as an "ideal".  I'd love any suggestions though.  Maybe the solution is at a different layer of my app.

**Comment by parsonsmatt** [comment]
@2piix The way you "should" do this is to have a different "wire" type than your database type. It is OK to share representation when they're the same, but you're running into different representations.

So you would have:

```haskell
data ApiUser = ApiUser { apiUserId :: Int, -- other fields etc }

apiToDb :: ApiUser -> Entity User
apiToDb = ...
```

**Comment by MHova** [comment]
> And, Primary and Unique can't be defined for the same field

Not sure if something's changed since the quoted [post](https://github.com/yesodweb/persistent/issues/309#issuecomment-57341487) was made in 2014, but as of right now you can indeed declare a field as both `Primary` and `Unique`, which solves this problem. For example:

```haskell
TestDb
  aKey     Text
  aValue   Text
  Primary  aKey
  UniqueTestKey aKey
  deriving Show Eq
```
