### ISSUE TITLE
Extend instance of Data.Map

### ISSUE THREAD

**Issue by fgaz** [yesodweb/persistent#360]
Why is the instance of PersistField for Data.Map limited to (Map Text PersistValue)? Is it possible to extend it to (Map PersistValue PersistValue)?
EDIT:
Ok, apparently it's a limitation of aeson. Sorry for missing that.
Still, is it possible to store directly, say, a (Map Int Int) without resorting to manually serializing/showing the key each time?

**Comment by snoyberg** [comment]
I suppose it would be theoretically possible to make such a typeclass instance, I don't see something inherently problematic. I suppose there are questions about what exactly would be the serialization/deserialization rules, but it's probably relatively straightforward. I can't guarantee acceptance, but I'd lean towards merging in such a pull request.

**Comment by gregwebs** [comment]
I created a branch for this change a while ago: https://github.com/yesodweb/persistent/tree/map-key-any

**Comment by gregwebs** [comment]
In MongoDB a map is first class database object, but keys are always text, which is why I think I did not bother to follow through. In Postgres, I would presume that jsonb is text keys only. So I don't think there is a benefit to changing persistent. But you can write a PersistField instance for the (new)type that you are using and have the serialization/de-serialization go on there.

**Comment by fgaz** [comment]
Added IntMap in #362
