### ISSUE TITLE
Foreign Key and ID types do not match on 32bit architectures

### ISSUE THREAD

**Issue by ivanperez-keera** [yesodweb/persistent#399]
Hi

On 32bit machines, the following model:
```
User
    ident    Text
    password Text Maybe
    name     Text Maybe
    UniqueUser ident
    deriving Typeable
Email
    email Text
    user UserId Maybe
    verkey Text Maybe
    UniqueEmail email
```
produces the following tables:

```
mysql> DESCRIBE email;
+--------+------------+------+-----+---------+----------------+
| Field  | Type       | Null | Key | Default | Extra          |
+--------+------------+------+-----+---------+----------------+
| id     | bigint(20) | NO   | PRI | NULL    | auto_increment |
| email  | text       | NO   | UNI | NULL    |                |
| user   | int(11)    | YES  | MUL | NULL    |                |
| verkey | text       | YES  |     | NULL    |                |
+--------+------------+------+-----+---------+----------------+
mysql> DESCRIBE user;
+----------+------------+------+-----+---------+----------------+
| Field    | Type       | Null | Key | Default | Extra          |
+----------+------------+------+-----+---------+----------------+
| id       | bigint(20) | NO   | PRI | NULL    | auto_increment |
| ident    | text       | NO   | UNI | NULL    |                |
| password | text       | YES  |     | NULL    |                |
| name     | text       | YES  |     | NULL    |                |
+----------+------------+------+-----+---------+----------------+
```
The types of ```user``` in the table ```email``` and ```id``` in the table ```user``` should match. Otherwise, foreign key constraints cannot be added. Yesod devel fails because of this.

See also: https://groups.google.com/forum/#!topic/yesodweb/DhciiGm3vBc

@gregwebs  pointed out the following:
* Are you on a 32 or 64 bit machine? I am thinking this issue must be attributed to the usage of the Int type resulting in different database types for different platforms:
 https://github.com/yesodweb/persistent/blob/a4f3b1fe7e8896b9bfaf5f4019e5af378296421c/persistent/Database/Persist/Sql/Class.hs#L212
* This points out that our testing is only done on 64 bit.

**Comment by meteficha** [comment]
I think #400's solution is a terrible idea.  

  * We should use `Int64` for keys on every platform.

  * There should be no mention of `Int` on the codebase except for giving it useful instances.

That commit (ac82709) now makes it impossible to use 32-bit and 64-bit binaries on the same database, unless I'm missing something.

**Comment by gregwebs** [comment]
#400 shows where the problem is and how to make the existing code consistent.

I agree it is not a great solution though. I think you are referring to the possibility for 1 client to be on a 32 bit machine and another to be on a 64 bit machine.

This is similar to the problem that the client binary that uses persistent may be compiled and ran on a different machine than the database exists on. So it would be possible for a client to be on 64 bits and MySQL to be on 32 bits, which would overflow when storing a Haskell Int that needs 64 bits.

I think what we really want to ensure that if `Int` is used the client and server `Int` should always match up. This check can only be performed when the connection pool is initialized.

But that is a change to the runtime behavior: we can still change the compile-time behavior.
A good change to make would be to just remove any instances for `Int` and force users to specify `Int32` or `Int64`. If that is too radical of a change, I would like to just presume the server and client are on a 64-bit machine and that `Int` means `Int64`. The few 32 bit users can switch their code to use `Int32`.

**Comment by meteficha** [comment]
So it seems there are two problems:

  * The type of default keys.  These should be always `Int64` IMHO.

  * The SQL type of `Int`.  Choosing 32/64 depending on the host is bad as we shouldn't change the schema because of this.  Choosing 64 bits at all times will make things silently break on 32 bit builds.  So I think there are only three possible solutions:
    1. Drop `Int` support.  I support this.  Being explicit about bit size is good (cf. Rust).
    1. Drop `Int` support on 32-bit builds.  Instead of failing corrupting things at runtime, we make the code fail at compile time.
    1. Make `Int` behave as 32 bits on both 32- and 64-bit platforms.

Strictly speaking, though, dropping `Int` support is the only solution.  The Haskell Report guarantees only 30 bits for `Int`.  IIRC, JHC tags `Int`s and thus provides them with less than 32 bits.  Unless we added a 30-bit integer SQL type.

**Comment by gregwebs** [comment]
I like the option of dropping Int support on 32-bit builds (assuming we want to maintain some backwards-compatibility). What is the preferred method for implementing that?

**Comment by meteficha** [comment]
We could use Cabal flag `arch(i386)` for removing the instance and, for defense-in-depth against refactoring, add a runtime check for `bitSize (0 :: Int) >= 64` (hopefully should be optimized away).

**Comment by snoyberg** [comment]
Instead of a runtime check, we could use Template Haskell to perform a compile-time check on `bitSize` and then not provide the instance in question. But I don't know how I feel about having code work on a 64-bit system but not a 32-bit system (this applies to both runtime and compile time checks). Simply dropping the `Int` instance and forcing usage of `Int64` in all cases may make more sense.

Caveat emptor: I haven't really thought through all of this very well yet.

**Comment by gregwebs** [comment]
The error for 32 bit users will occur at compile time and will produce a meaningful error message.

I agree that dropping `Int` support in the long term is best. However, we should make as many intermediate steps as possible. These changes are already going to require changes for 32 bit users and 64 bit users will also have to `import Data.Int (Int64)`. So I would prefer we merge and release #402 as is and have @ivanperez-keera test it out. Then we can create an issue to remind us to remove the instance in an upcoming release.

**Comment by gregwebs** [comment]
@ivanperez-keera can you upgrade to persistent-template 2.1.3.3 now? We still probably need a new release of persistent for you in addition to that.
