### ISSUE TITLE
Connection string using URI in Sqlite

### ISSUE THREAD

**Issue by phonje** [yesodweb/persistent#526]
The connection functions of the persistent-sqlite packege seem not to accept a connection string in URI format. For excample,

    withSqliteConn "file:///tmp/test.db" $ runSqlConn $ do ...
    withSqliteConn "file:test.db?mode=memory" $ runSqlConn $ do ...

In the former case, the error which can't open the file occurs. In the latter case, the database file of the same name (that is "file:test.db?mode=memory") is made in the current directory.

Is this a bug or a feature?

**Comment by snoyberg** [comment]
Does sqlite itself support such a query string format?

**Comment by phonje** [comment]
Yes, Sqlite does.
https://www.sqlite.org/uri.html

And that, the connection functions included in other packeages (e.c. sqlite-simple) accept URI.

**Comment by phonje** [comment]
Sorry, I overlooked that the URI filename capability is disabled by default in Sqlite. It isn't wrong that persistent-sqlite doesn't support the URI, is it?

I expect that persisten-sqlite will support the URI in the near future.

thunks.

**Comment by meteficha** [comment]
I'm opposed to changing `withSqliteConn`'s behavior, but I'd be okay with a new `withSqliteURIConn` or something.

**Comment by snoyberg** [comment]
What's the reason for the opposition Felipe? I understand that it's
technically a breaking change, but I'm having trouble imagining a real
world scenario where someone would have a connection string that would
parse as a URL.

I'm any event, a PR adding this feature as a new function will definitely
be accepted, and should be fairly straightforward to add.

**Comment by meteficha** [comment]
Most uses of `persistent-sqlite` use plain old files.  Proof: that's the only thing we support right now.  Besides the backwards compatibility bit, which we shouldn't forget that also includes printed documentation, it's better to keep a straightforward `FilePath` as the main API.  Finally, I don't see a compelling reason to change the current API instead of adding a new function.

**Comment by rubenmoor** [comment]
I'm working on a different pull request that would allow read-only access to databases. Both, my pull request and the uri feature, require the move to `sqlite_open_v2`. While I'm at it: I could add an optional "URL" parameter to the connection string that would set the URI flag and thus allow for uris instead of filenames.

If I get it right, the URL parameter might be redundant, though:

The Sqlite docs say

> SQLite uses the "file:" URI syntax to identify database files.

https://www.sqlite.org/uri.html

It should simply be set by default, to allow urls, identified by "file:...", in my opinion.

(Ironically, with the uri syntax my whole read-only thing is redundant, as the query parameter  "mode=ro" would do the same thing :S)

**Comment by MaxGabriel** [comment]
If I understand it right, supporting the query string sounds much better than rewriting parsing code for all potential SQLite configuration options

**Comment by rubenmoor** [comment]
Sqlite docs say:

> It is an error to specify a value for the mode parameter that is less restrictive than that specified by the flags passed in the third parameter to sqlite3_open_v2().

https://www.sqlite.org/c3ref/open.html

I understand it that the flags should then be `READWRITE | CREATE | URI` where only the URI flag is new. For read-only access (more restrictive) I can pass a mode in the uri.

That is now reflected in the [pull request](https://github.com/yesodweb/persistent/pull/418).

**Comment by rubenmoor** [comment]
Documentation: I added a "URI Filenames" paragraph in the Sqlite section.

https://github.com/yesodweb/persistent/wiki/Database-Configuration

**Comment by MaxGabriel** [comment]
Implemented by #418; closing
