### ISSUE TITLE
persistent-redis fails to build on GHC 8.0.1

### ISSUE THREAD

**Issue by psibi** [yesodweb/persistent#567]
Error log: https://hydra.nixos.org/build/36486380

**Comment by gregwebs** [comment]
Doesn't necessarily seem like a version 8 issue. persistent-redis is in need of a little maintenance now.

**Comment by paulrzcz** [comment]
I will try to find a spare time to make this maintenance today if nobody has started it yet.

**Comment by gregwebs** [comment]
Thanks! I started messing around with a GHC 8 build with stack here: https://github.com/yesodweb/persistent/pull/568

**Comment by paulrzcz** [comment]
I've just fixed persistent-redis locally to be buildable with current persistent and GHC 7.10.3 in lts-5.1.

Though I would like to pose a restriction on the lower bound of persistent. Which version of persistent was the split of PersistStore to PersistStoreRead/Write introduced in?

Also could I commit the patch directly into main branch because I have rights to do so? Or do you have another process for contributors?

**Comment by gregwebs** [comment]
Its always best to create a pull request first.
We are trying to maintain a decent ChangeLog now. 2.5 had the split:
https://github.com/yesodweb/persistent/blob/master/persistent/ChangeLog.md#25

we should get Redis into the Travis build if we can which will help prevent it from falling behind again.

**Comment by paulrzcz** [comment]
I've just merged the pull request with persistent 2.5 compatibility but it still fails on GHC 8.0.1. I am going to finally setup the newest version of GHC and to figure out what's going on.

**Comment by paulrzcz** [comment]
The version 2.5.1 should be ok on GHC 8.0.1

**Comment by psibi** [comment]
Closing the issue since it's fixed.
