### ISSUE TITLE
Feature request and RFC: Audit log

### ISSUE THREAD

**Issue by saurabhnanda** [yesodweb/persistent#598]
Coming from a Rails/ActiveRecord background, I'm finding a lot of impedance mismatch between my regular through-process and the abstractions available in Persistent. I'm unsure if it's just that (impedance mismatch) or whether Persistent genuinely lacks some features available in ActiveRecord.

For example, audit logs. 

Consider this as a feature request for audit-logs built into Persistent. Here are my thoughts about how this could be solved: https://gist.github.com/saurabhnanda/2271b5e1af2af77db9db9f6e14f5c12c

**Comment by gregwebs** [comment]
Its a combination of the 2. Persistent is not actually an "ORM" because it doesn't work with objects based on user-defined classes with hooks, etc. This makes persistent lower-level but really easy to understand how it operates, whereas in Rails you will often be surprised when the ORM does or does not kick-in, for example when you do a batch insert and your callbacks are not triggered.

The above happens in part because the Rails ORM is trying to do everything and keep the database dumb. This begs the question: what database are you using? Is it possible to implement your audit log in the database itself? This makes for much better auditing when a process other than your Haskell app modifies the DB.

If you do try to implement this in the Haskell application, I don't know that you need a global query cache to avoid fetching the old version. Presumably you have the old version as an `Entity` constructor because you just fetched it and your persistent wrapper function can take that `Entity` rather than just a `Key`. But you could certainly do the query cache approach with wrapper functions. Just have the fetches write to an `IORef` of your HashMap.

I view Persistent as a lower-level entity tool to enable you to safely write your modeling layer. You should be able to add auditing to your modeling layer. I am doing this in an application right now but I need to review how to do this in a more rigorous and type-safe way.

**Comment by dfordivam** [comment]
@saurabhnanda I have had a similar requirement, and have written a small wrapper library code to this. The main intention here was to avoid boilerplate code. You can try it out to see if its useful [https://github.com/dfordivam/persistent-cdc](https://github.com/dfordivam/persistent-cdc).

**Comment by parsonsmatt** [comment]
The appropriate place for this would be a library built on top of `persistent`, like @dfordivam wrote (nice!).
