### ISSUE TITLE
Drop GHC 7.8 support soon?

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/persistent#744]
I was recently running into some CI test failures because a function I imported was only used in an `#if MIN_VERSION_base(4,8,0)` code block. It wasn't a big deal to work around, but my understanding is that Yesod packages only try to support the last three releases of GHC. With the release of GHC 8.2.2, dropping 7.8 support seems reasonable.

There are 12 instances of `#if MIN_VERSION_base(4,8,0)` across the persistent codebase (as well as several 4.6.0 and 4.7.0 ifdefs that can be dropped).

This would mainly entail deleting the CPP macros, bumping the required version of base, and updating the travis config to not use LTS-2.

Probably it'd be good to wait at least until GHC 8.2.2 is on LTS Haskell, though.

**Comment by paul-rouse** [comment]
I have no problem dropping 7.8 once 8.2 is in an LTS.  We can get rid of that horrible conditional installation of `happy` I recently had to put in the travis config:smile:

We should take care, though, since there are non-Yesod packages depending on `persistent`, too.  Do you know how many past GHC versions the wider community expects to have supported?  A cursory look through the "used by" section of https://www.stackage.org/lts-9.14/package/persistent-2.7.1 shows a couple of snaplets, a servant auth package, an apiary package (not sure whether that's maintained), and several others which have no dependency on Yesod.

**Comment by bergmark** [comment]
You may also want to consider using [base-compat](https://hackage.haskell.org/package/base-compat) and other -compat packages. It makes it a lot easier to keep support for older GHCs

**Comment by rwobben** [comment]
I can try and if I understand it well all the  4.8.0 and lower must be deleted ?

**Comment by MaxGabriel** [comment]
@rwobben Yes that's correct. You may want to base your work off [this branch](https://github.com/yesodweb/persistent/pull/773), otherwise you'll run into merge conflicts when that PR gets merged

**Comment by rwobben** [comment]
oke, I asked there questions because it's not clear to me how the branch is named.

**Comment by hdgarrood** [comment]
Suggest closing this since `persistent.cabal` now specifies a lower bound on `base 4.9`, which means that the oldest supported GHC is 8.0?
