### ISSUE TITLE
[mysql] Specifying sqltype=double(6,5) or sqltype=mediumtext causes repeated migrations

### ISSUE THREAD

**Issue by dgaw** [yesodweb/persistent#752]
It looks like choosing a custom sqltype for a Text or a Double causes a repeated, unnecessary migration every time runMigration is called.

Example
```
Page
    ...
    content T.Text Maybe sqltype=mediumtext
    score Double sqltype=double(6,5)
    ...
```
This causes 2 alter table statements to be executed every time I run my app:
```
Migrating: ALTER TABLE `page` CHANGE `content` `content` mediumtext NULL
Migrating: ALTER TABLE `page` CHANGE `score` `score` double(6,5) NOT NULL
```

I'm using persistent 2.7.1 and persistent-mysql 2.6.2.

**Comment by MaxGabriel** [comment]
I reproduced this with this test case, based off of [the one here](https://github.com/yesodweb/persistent/pull/742/files)

```
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE QuasiQuotes, TemplateHaskell, CPP, GADTs, TypeFamilies, OverloadedStrings, FlexibleContexts, EmptyDataDecls  #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
module MigrationIdempotencyTest where

import Database.Persist.TH
import qualified Data.Text as T

import Init

#ifdef WITH_NOSQL
mkPersist persistSettings [persistUpperCase|
#else
share [mkPersist sqlSettings, mkMigrate "migration"] [persistLowerCase|
#endif
Idempotency
    field1 Int
    field2 T.Text sqltype=varchar(5)
    field3 T.Text sqltype=mediumtext
    field4 Double sqltype=double(6,5)
|]


specs :: Spec
specs = describe "Migration" $ do
#ifdef WITH_NOSQL
    return ()
#else
  it "is idempotent" $ db $ do
      again <- getMigration migration
      liftIO $ again @?= []
#endif
```

Based on the test failures, it's not all custom sqltypes for a Text or Double. In the test above, the migrations I got were:

```
 ["ALTER TABLE `idempotency` CHANGE `field3` `field3` mediumtext NOT NULL","ALTER TABLE `idempotency` CHANGE `field4` `field4` double(6,5) NOT NULL"]
```

So `field2`, with a custom type of `varchar(5)`, stayed the same between migrations.

**Comment by MaxGabriel** [comment]
Ok, here's what I think the problem is internally:

`ColumnInfo` has enough information to make the correct migration, namely `ciColumnType`, which is something like `double(6,5)`.

-- | Extra column information from MySQL schema
data ColumnInfo = ColumnInfo
  { ciColumnType :: Text
  , ciMaxLength :: Maybe Integer
  , ciNumericPrecision :: PersistValue
  , ciNumericScale :: PersistValue
  }

`ColumnInfo` is only used by `getColumn`, which passes the data to `parseColumnType` and returns a `SqlType`. This data is passed up the chain from `getColumn`, to `getColumns`, to `migrate'`, which uses it to call `getAlters`, which uses it to call `findAlters`, which does this comparison between the old column (from the database) and the new column (from the persistent definition):

```
-- Type and nullability
modType | showSqlType type_ maxLen False `ciEquals` showSqlType type_' maxLen' False && isNull == isNull' = []
        | otherwise = [(name, Change col)]
```

And `showSqlType` can only return TEXT or VARCHAR, so there's no way it'll match what's in the Persistent model definition (MEDIUMTEXT):

```
showSqlType SqlString  Nothing    True  = "TEXT CHARACTER SET utf8"
showSqlType SqlString  Nothing    False = "TEXT"
showSqlType SqlString  (Just i)   True  = "VARCHAR(" ++ show i ++ ") CHARACTER SET utf8"
showSqlType SqlString  (Just i)   False = "VARCHAR(" ++ show i ++ ")"
...
showSqlType (SqlOther t) _        _     = T.unpack t
```

A quick fix, which may cause problems elsewhere (although all the tests pass), is changing `parseColumnType`. It has code like this:

```
parseColumnType "text" _                                       = return (SqlString, Nothing)
parseColumnType "mediumtext" _                                 = return (SqlString, Nothing)
parseColumnType "longtext" _                                   = return (SqlString, Nothing)
...
parseColumnType _ ci                                           = return (SqlOther (ciColumnType ci), Nothing)
```

and if you comment out the `mediumtext` line, you'll no longer get duplicate migrations for mediumtext (because it'll fall into the SqlOther category, which has its exact type of `mediumtext`). Similarly, we can make this change for `double`, which requires the column type to be exactly double, not e.g. `double(5,6)`.

```
parseColumnType x@("double") ci | ciColumnType ci == x         = return (SqlReal, Nothing)
...
parseColumnType _ ci                                           = return (SqlOther (ciColumnType ci), Nothing)
```

These changes will fix the failing test I made above.

The main problem I can think with this solution is that now anyone who's reading mediumtext from their database will get a `SqlOther`, not a `SqlString` (I'm pretty sure, haven't confirmed). So probably a better solution that mine is necessary.

**Comment by paul-rouse** [comment]
It looks to me as if `persistent-mysql` misuses `SqlType`.  The [documentation](https://hackage.haskell.org/package/persistent-2.7.1/docs/Database-Persist-Types.html#t:SqlType) seems to say that a backend-specific type should be in `SqlOther`.

This is actually a very recent change - #678 - and I don't understand why it was done.  I have been using `longtext` in production well before this change, and I have not noticed any issues with it at all.  In fact, my production code is still using the version prior to this change.  (I also have a `longblob` in that application, which is presumably also broken now.)

#678  didn't get a changelog entry, either, which doesn't help, but it seems to have gone in at 2.6.2 - only six weeks ago.  I think we have the option of reverting that change - what do you think @MaxGabriel?

**Comment by MaxGabriel** [comment]
Oh that’s great @paul-rouse. Reverting sounds good to me, but I’d like to hear from the author of #678 / maybe look into this just a little more

**Comment by dgaw** [comment]
I'm also for reverting #678. I'd used "mediumtext" for months before that change without a problem. 

"Double" could use the workaround suggested by @MaxGabriel. It works just fine, at least for my use case. :)

**Comment by MaxGabriel** [comment]
@dgaw Would you be interested in writing a pull request for this, with the test I wrote above, the change for double, and a revert of #678?

**Comment by dgaw** [comment]
@MaxGabriel Sure, leave it with me.
