### ISSUE TITLE
Export `Connection` constructor from persistent-sqlite's Database.Sqlite

### ISSUE THREAD

**Issue by merijn** [yesodweb/persistent#771]
Persistent allows use of rawSql for more complicated queries, but the persistent-sqlite interface is extremely limited compared to the interface exposed by SQLite itself, limiting what can be done using rawSql (For example, no custom collation/function creation, etc.).

If the raw database pointer in the underlying connection is accessible power users can use the SQLite C API to perform any functionality not exposed by `persistent-sqlite`. Alternatively, people strongly prefer restricting access to the raw database pointer for safety reasons, I'd be ok with implementing the functionality myself in persistent-sqlite and exposing safer primitives to use them, but I would prefer knowing if there's any chance of getting that merged back into persistent-sqlite before I invest the effort.

**Comment by merijn** [comment]
The easiest approach is probably to move the Connection and Statement newtypes into a new module `Database.Sqlite.Unsafe` and then import that into `Database.Sqlite` only re-exporting the types, but not the constructors. This means that anyone like me can simply import the Unsafe method and use SQLite's API directly via the API without issue, which should not impact existing code at all (in fact, this would be like a 5 line patch). Any comments? Objections?

**Comment by MaxGabriel** [comment]
Sorry for the slow response. I’m good with the unsafe approach. Can you call the module Internal, and say that the functions are not covered by normal PVP versioning (ie if they change it’s not a breaking change)

**Comment by merijn** [comment]
I'm still thinking how to add a nice variant of `withSqliteConn` that exposes the raw `Connection`, but it's tricky, because I can't simply extend the `SqlBackend` with the pointer. I'm still figuring out how to nicely wrap that up and will probably add another commit/PR for that when I figure it out.

**Comment by psibi** [comment]
@merijn New to this whole issue and since you have linked this one from the previous discussion ( https://github.com/yesodweb/persistent/issues/783#issuecomment-453741841 ), I'm commenting here. I saw the corresponding PR to this issue and was wondering if your problem will be solved by exporting two functions like this:

```
unsafeRawConnectionPointer :: Connection -> Ptr ()
unsafeConstructor :: Ptr () -> Connection
```

Is there a reason why something like above won't work ?

**Comment by merijn** [comment]
I mean, in essence that's what the other PR does. But since I sometimes change/rebind functions I need to keep the Ptr around, so the only other thing it really does is (effectively) adding `BackendCompatible` instances for `(SqlBackend, Ptr ())` (but wrapped in a newtype).

I'm open to other approaches, but at the time there was a push to switch from the `IsSqlBackend` constraint to `BackendCompatible`, but that work seems to have never really finished.

**Comment by psibi** [comment]
@merijn I looked your PR and I still feel that the approach I mentioned above is a lot more easier to understand and maintain. Do you feel strongly about PR #772 design ? If you can change it to the above one, I can accept the PR. Free feel to tell your opinions, I'm open to change.

@MaxGabriel Let me know if you think otherwise.
