### ISSUE TITLE
`withPostgresqlConn` giving Access violation error

### ISSUE THREAD

**Issue by tysonzero** [yesodweb/persistent#794]
OS: Windows 10 Enterprise Version 1709

Stack: Version 1.6.5, Resolver 10.2

persistent 2.7.1
persistent-postgresql 2.6.2.1
postgresql-libpq 0.9.3.1
postgresql-simple 0.5.3.0

Postgres: Version 10.3

Minimal code example:

    main = runNoLoggingT . withPostgresqlConn "<connection string>" . runReaderT @SqlBackend $ pure ()

Error:

    Access violation in generated code when executing data at 000000008000fb50

**Comment by MaxGabriel** [comment]
Sounds like a GHC bug :(

This might be the relevant ticket: https://ghc.haskell.org/trac/ghc/ticket/13112

**Comment by tysonzero** [comment]
I have looked at that ticket and tried using `-fexternal-interpreter` to fix the issue, but I still get the same error. There is a good chance that is what's going on, but unfortunately I'm still in a tough spot regardless.

**Comment by MaxGabriel** [comment]
Darn. I guess just comment on the GHC ticket to encourage someone to solve it?

**Comment by tysonzero** [comment]
Will do. This is a pretty big blocker and may require me to switch OS's, so I hope it will be fixed soon.

**Comment by RyanGlScott** [comment]
@tysonzero, I am unable to reproduce the segfault with the program in https://github.com/yesodweb/persistent/issues/794#issue-302209255. (I also commented to this effect on the Trac ticket [here](https://ghc.haskell.org/trac/ghc/ticket/13112#comment:22)).

Echoing @Mistuke's comments [here](https://github.com/yesodweb/persistent/issues/697#issuecomment-338428262), one thing you could try is to build this program with GHC 8.4 and, if it also segfaults, run the program with `+RTS --generate-crash-dumps` to generate a crash dump.

**Comment by tysonzero** [comment]
@RyanGlScott Do you have a postgresql db + associated working query string you can test it out on, with "<connection string>" verbatim I don't get an access violation error either. I can look into the` +RTS --generate-crash-dumps` thing soon, thanks.

**Comment by RyanGlScott** [comment]
I have the MinGW-w64 libraries for `postgres` (`mingw-w64-x86_64-postgresql`) installed, which was necessary to build `postgres-libpq`. Other than that, I don't know what kind of setup is needed to run `persistent-postgresql` programs. In particular, I don't know what the phrase "postgresql db + associated working query string" means—can you walk me through how I'd set one up?

**Comment by Mistuke** [comment]
The problem is, that this example just isn't very minimal. The dependency chain is actually very huge. I have two suggestions to attempt to get this fixed sooner:

1) try to minimize the example by copying the definitions of the functions used into one hs file and not needing any other external library aside from `postgresql-libpq` which seems to be the lowest level binding. This would speed the process up immensely.

2) Are you able to create an executable? does the executable segfault? if both to yes, try using https://docs.microsoft.com/en-us/sysinternals/downloads/procdump to generate a dump. 

If it's crashing during compilation, find the actual command being sent to GHC, and retry that, once you have the command that crashes, use procdump on GHC or copy and zip all the files the command is referring to so I can reproduce it (ideal).

**Comment by tysonzero** [comment]
@RyanGlScott So you will need to replace `"<connection string>"` with something like `"host=localhost port=5432 dbname=yourdbname user=yourusername password=yourpassword"`. Besides that you just need to have a postgresql db running with matching dbname, username and password.

@Mistuke Alright thanks, when I get back on the windows machine in question I will look into those steps. To be clear it is crashing during execution, not during compilation.

**Comment by Mistuke** [comment]
@tysonzero ok, that makes it a lot easier, also doesn't seem likely to be the same bug as the one linked to.
Can you reproduce it if you compile the program with `-debug`? if so compile with that, and use `procdump.exe -t -ma -e 1 -x . <program>.exe` and upload both the exe and crash dump. Also include the exact GHC version (check GHC --info, it should give a version and git hash).

**Comment by tysonzero** [comment]
@RyanGlScott 

I obtained postgresql from [here](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads), version 10.3.

And yeah my bad, I should have run `stack ghc -- --info`.

     ,("Project version","8.2.2")
     ,("Project Git commit id","0156a3d815b784510a980621fdcb9c5b23826f1e")
     ,("Booter version","8.0.2")

**Comment by Mistuke** [comment]
Is this the same binary that created the dump? The original one is called `baseball.exe`. Did you just rename it or recompiled?

Anyway, this isn't the same issue as the TH one. This has bugcode `APPLICATION_FAULT_SOFTWARE_NX_FAULT_INVALID_POINTER_EXECUTE` it tried to execute something that's not code. It also seems to happen out of program code, likely in one of the dll dependencies. I'll continue looking tomorrow.

**Comment by Mistuke** [comment]
@tysonzero I need another piece of information from you. I'm looking for the temporary object files the compiler created when building this. With `cabal` these would be in the `dist` folder, but don't know where stack places them. In Particular I'm looking for all `.o` file produced when compiling `postgres-libpq`. In particular `Database/PostgreSQL/LibPQ.o`.

**Comment by RyanGlScott** [comment]
Wow, I just managed to reproduce the issue:

```
$ ./Bug.exe
Access violation in generated code when executing data at 0000000014a87e00
$ ./Bug.exe
Access violation in generated code when executing data at 0000000007e07e00
```

It appears to have a different memory address each time.

Sure enough, you have to download PostgreSQL from [here](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) in order to trigger the issue. The MinGW-w64 version does not appear to suffer from this issue.

**Comment by RyanGlScott** [comment]
Here's an example which only depends on `postgresql-simple`:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# OPTIONS_GHC -Wall #-}
module Main where

import Database.PostgreSQL.Simple

main :: IO ()
main = do
  conn <- connectPostgreSQL "host=localhost port=5432 dbname=dbname user=postgres password=password"
  [Only (_ :: String)] <- query_ conn "show server_version"
  return ()
```
```
$ ./Bug2.exe
Access violation in generated code when executing data at 0000000014a87e00
```

I'll try to minimize this further.

**Comment by RyanGlScott** [comment]
I chatted with @Mistuke about this this afternoon. He can give the full story, but the short version is that this segfault happens due to a deficiency of `ld`, which I've reported upstream as https://sourceware.org/bugzilla/show_bug.cgi?id=22948.

For the time being, I believe the proper way to work around this is to change `postgresql-libpq` to link against `libpq` instead of `pq`. I've submitted a patch [here](https://github.com/lpsmith/postgresql-libpq/pull/45), so if you're impatient while waiting for that to be merged, you can use my fork of `postgresql-libpq` in the meantime. (I've confirmed that this works with both the official Windows PostgreSQL distribution as well as the MinGW-w64 version.)

**Comment by Mistuke** [comment]
As @RyanGlScott mentioned, this isn't a bug in GHC. The issue can be explained by this simple C program

```
#include <stdio.h>
#include <stdint.h>

extern void* PQgetvalue (void);

int main () {
  printf ("PQgetvalue: %p", PQgetvalue);
}
````

The idea of which is to print the address of the function.

Compiling it against the "official" distribution and the mingw-w64 one you get

```
Tamar@Rage MINGW64 /r                                               
$ gcc test.c -o test -lpq -L/E/Program\ Files/PostgreSQL/10/lib/                       
Tamar@Rage MINGW64 /r                                               
$ ./test.exe                                                        
PQgetvalue: 00000000`6440CDE0
                                     
Tamar@Rage MINGW64 /r                                               
$ gcc test.c -o test -llibpq -L/E/Program\ Files/PostgreSQL/10/lib/                          
Tamar@Rage MINGW64 /r                                               
$ ./test.exe                                                        
PQgetvalue: 00000000`004015A0
```

As you see, the first one results in the function being in a significantly larger memory offset. In this case it still fitted, however...

Now if we look at your dump it shows

```
0x000ab360: C:\Program Files\PostgreSQL\10\bin\LIBPQ.dll
      Base   0x180000000  EntryPoint  0x180021968  Size        0x00049000    DdagNode     0x000ab4b0
      Flags  0x000c22ec  TlsIndex    0x00000000  LoadCount   0x00000001    NodeRefCount 0x00000000
             <unknown>
             LDRP_LOAD_NOTIFICATIONS_SENT
             LDRP_IMAGE_DLL
             LDRP_DONT_CALL_FOR_THREADS
             LDRP_PROCESS_ATTACH_CALLED
```

That is the DLL has a prefered `imageBase` is at `0x180000000`, e.g. in the `64 bit` address range. 

However the call translates to a `R_X86_64_PC32` relocation. e.g, it has to fit in a `32 bit` address. I'm surprised LD wasn't telling you during linking that the `R_X86_64_PC32` is being truncated to fit.

In your case your function is at `0x000000018000fb50`, but because it has to fit, it's truncated to `0x8000fb50` and you segfault.

This is partly why you don't link against dlls directly usually, though LD does support this "feature". What's happening is then you specify `extra-libraries: pq` LD can't find the `.lib` import library (it does find the `libpq.dll.a` from mingw-w64 if you used that.) because it searches for `xxx.lib` instead of `libxxx.lib`.

The simplest solution for you right now is in `C:\Program Files\PostgreSQL\10\lib` copy `libpq.lib` to `pq.lib` leaving both options. It should then work after a re-compile. Note you have to re-compile everything.

**Comment by RyanGlScott** [comment]
Actually, [`postgresql-libpq-0.9.4.1`](http://hackage.haskell.org/package/postgresql-libpq-0.9.4.1) was just released with a workaround for this issue! So you might be able to get by with just that.

**Comment by Meshu** [comment]
Wow, thank you very much to every one in this thread for such diligent and masterful bug hunting.
Bonus points for being educational at the same time, learnt a couple new things !

**Comment by MaxGabriel** [comment]
Yeah, this was pretty awesome to watch unfold!

**Comment by tysonzero** [comment]
Thank you so much guys, works just fine now!

**Comment by RyanGlScott** [comment]
Excellent. Can this issue be closed, then?

**Comment by tysonzero** [comment]
Yeah sure.
