### ISSUE TITLE
Adding threading mode flags to sqlite3_open_v2 foreign call?

### ISSUE THREAD

**Issue by ghost** [yesodweb/persistent#811]
I'd like to be able to set the [threading mode](https://sqlite.org/threadsafe.html) of sqlite operations when the connection is opened.  

I [see](https://www.stackage.org/haddock/lts-11.10/persistent-sqlite-2.8.1.2/src/Database.Sqlite.html#openError) that it would be simple to set a default threading mode, but that might not be suitable for all users.  

[Here](https://www.sqlite.org/c3ref/c_open_autoproxy.html) is the reference for the pertinent flags.

Would it be advisable to produce a new collection of functions to facilitate the alternate threading modes that one might wish to apply to a connection?  Or would it be better to attempt to generalize the existing functions to accept threading mode options?

**Comment by asciiascetic** [comment]
An alternate approach would be to to elaborate on the interface to `sqlite3_config` that, at the moment, seems to only have a place in the custom foreign call to `persistent_sqlite_set_log`.  

Maybe I could add another file to `cbits` that includes an implementation of, say, `persistent_sqlite_set_threading` ? Then add the appropriate field to `Config` ?

**Comment by asciiascetic** [comment]
It seems like [this pr](https://github.com/yesodweb/persistent/pull/772) will actually cover my needs. 

Any movement there?

**Comment by merijn** [comment]
@ghost That PR is mostly blocked on #783, and I haven't had time to dive into finalising those due to work on my thesis. I've just been relying on using my git branch directly in my own code for now as I didn't have time to figure #783 out next to the work on my thesis (and I won't be able to commit time to figuring that out until the end of the year).

If someone dives in and sorts out the whole redundant and messy typeclass/constraint stuff discussed in #783 (which, honestly, shouldn't be hard just a bunch of work), then I can update/finalise the raw-sqlite-ptr branch/PR in an afternoon and then it's good to go.

**Comment by merijn** [comment]
@ghost You'll be happy to learn that PR has finally been merged and released ;)

**Comment by parsonsmatt** [comment]
Good catch :)
