### ISSUE TITLE
Feature request: Generate `enum` types in Postgresql

### ISSUE THREAD

**Issue by parsonsmatt** [yesodweb/persistent#861]
It'd be nice to have sum types be user created `ENUM` types for additional type-safety in the presence of other non-`persistent` database users.

To do this, you'd want to:

- define the type itself along with the constructors/values
- migrate the type, either
  - create if it does not exist,
  - add missing values if it does exist,
  - or error if values have been removed.

**Comment by parsonsmatt** [comment]
(this is something that can somewhat easily be defined in a library and later folded in to `persistent` if the library PoC works out, so I am going to just do that)

**Comment by MaxGabriel** [comment]
We do all our migrations with Standalone Migrations (just active record migrations basically), and make heavy use of enums (we even use them in a lot of places instead of booleans). This might be helpful:

1. You need to disable transactions to add a value to a Postgres enum
2. I wrote some TH code to generate PersistField and PersistFieldSql instances if you'd like to steal that: https://github.com/yesodweb/persistent/issues/792

**Comment by parsonsmatt** [comment]
Awesome :smile: Glad to know that it is something that's wanted!

**Comment by parsonsmatt** [comment]
Closing as a dupe of #792
