### ISSUE TITLE
Ability to add DOMAIN types (Postgres specific maybe?)

### ISSUE THREAD

**Issue by erikd** [yesodweb/persistent#952]
Using PostgreSQL I currently have a relatively complex system of running a set of migrations in order. One of the early stages in these migrations sets up some `DOMAIN` types using statements like:
```
CREATE DOMAIN hash32type AS bytea
  CHECK (octet_length (VALUE) = 32);
```
which are later used in the Persistent schema definitions as:
```
  Table
    column                ByteString          sqltype=hash32type
```
it would be nice to be able to specify these domain types as part of the schema definition EDSL.

If we can hash out what this should look like, I will almost certainly have a crack at implementing it. We should probably add a way to define Postgres `VIEW`s this way at the same time. I realize that this is likely a significant overhaul of the TH EDSL.

**Comment by parsonsmatt** [comment]
I don't think this is in scope for the EDSL. It'd be easier to implement directly in Haskell functions IMO.

`VIEW`s are definitely out-of-scope for `persistent`, but would be great in `esqueleto`.

Fwiw, you should probably do something like the following for that specific example:

```haskell
newtype Hash32 = Hash32 ByteString

instance PersistField Hash32 where
  toPersistValue (Hash32 bs) = PersistDbSpecific bs
  fromPersistValue (PersistDbSpecific bs) = Hash32
  fromPersistValue x = error $ show x

instance PersistFieldSql Hash32 where
  sqlType _ = SqlOther "hash32type"
```

Then you don't need to use the custom `sqltype=hash32type`. Also allows you to express preconditions in the Haskell type etc - perhaps you've got `mkHash32 :: ByteString -> Either String Hash32` but can bypass `Left` checking for values in the database due to preconditions.

What would you like the API to look like for the `CREATE DOMAIN` functions?

**Comment by erikd** [comment]
Your solution to works to make sure the Haskell values are correct, where as `DOMAIN` types use PostgreSQL to enforce the constraints. Your suggestion puts the `ByteString` size constraint in the Haskell code so the Haskell code throws an error when data from the DB contravenes the size constraint . The `DOMAIN` constraint on the other hand prevents something of the wrong size being inserted into the DB.

> What would you like the API to look like for the CREATE DOMAIN functions?

When I raised this ticket, I had no idea, but I am beginning to think it should be a separate QQ or EDSL much like `mkMigrate`, `mkPersist` etc.

**Comment by parsonsmatt** [comment]
> Your solution to works to make sure the Haskell values are correct, where as DOMAIN types use PostgreSQL to enforce the constraints. Your suggestion puts the ByteString size constraint in the Haskell code so the Haskell code throws an error when data from the DB contravenes the size constraint . The DOMAIN constraint on the other hand prevents something of the wrong size being inserted into the DB.

I don't mean to *not* use the `DOMAIN` in Postgres. I just mean that you should probably have Haskell types that map to that domain. Otherwise you lose the information given by the database constraints when it is deserialized in Haskell.

The `sqlType _ = SqlOther "hash32type"` means that the default column type for a value with that Haskell type is `hash32type`. So having a `newtype Hash32 = Hash32 ByteString` with those instances would let you write:

```
Entity
  field1   Hash32
```

And the `PersistFieldSql` instance tells the database what underlying type to use.

> As for VIEWs, I think it is (at least potentially) something for Persistent.

I suppose this depends on what you're looking to do.

`persistent` is not SQL-only, as much as I might like it to be. `persistent` explicitly does not cover advanced SQL or MongoDB or Zookeeper features, in favor of providing a simpler interface for "common case" stuff. `esqueleto` is the library that adds `JOIN`s etc to `persistent` (though another library could be created and used side-by-side; the `EntityDef` and `PersistField` types are quite flexible).

**Comment by parsonsmatt** [comment]
>  It'd be easier to implement directly in Haskell functions IMO.

Expanding on this, you can write the following code today:

```haskell
rawExecute "CREATE DOMAIN hash32 AS bytea CHECK (octet_length(VALUE) = 32)" []
```

This would be a super useful feature to have, but it can be built out as a separate library. I'm going to close this as a won't-fix for now.
