### ISSUE TITLE
invalid input syntax for type bytea

### ISSUE THREAD

**Issue by brandon-leapyear** [yesodweb/persistent#997]
We have a model that can contain arbitrary JSON, so we created a `PersistField` instance for aeson's `Value`:
```haskell
instance PersistField Value where
  toPersistValue = toPersistValueJSON
  fromPersistValue = fromPersistValueJSON

instance PersistFieldSql Value where
  sqlType _ = SqlBlob
```
The problem comes when inserting a string with an escaped quotation mark:
```haskell
insert $ Foo "\""
```

The original problem we were having was the following line in the postgres logs:
```
UPDATE "column_filter" SET "operator"='"IN"',"rhs_value"='[";P\"p?6AjRC"]' WHERE "id"=17
```
As you can see, there is an escaped `\"` character, which should be doubly escaped: once for the JSON encoding in Haskell, and once for inserting into postgres. I believe inserting `\"` into postgres should insert `\\"`, so that Haskell reads `\"` from the database, and aeson parses an escaped `"` from there.

For the time being, it seems like `SqlBlob` is not the correct choice anyway; it should be `SqlString`, since `toPersistValueJSON` returns `PersistText`. But I figured this was a pretty important bug to submit.

**Comment by parsonsmatt** [comment]
I don't follow what's going on here. The `PersistField` instance for `Value` looks okay, but as you mention the `SqlString` is probably more appropriate. You say the problem is with `Foo`, but that type is using a string literal, and the only way that'd be a `Value` is if you had an orphan instance of `IsString Value` that was behaving poorly.

Can you post a minimal reproduction, with all types defined?

**Comment by brandon-leapyear** [comment]
Value already has an [`IsString` instance](https://www.stackage.org/haddock/lts-14.8/aeson-1.4.5.0/src/Data.Aeson.Types.Internal.html#line-384)?

**Comment by brandon-leapyear** [comment]
```haskell
module ValueOrphan () where

import Data.Aeson (Value)
import Database.Persist (PersistField(..), SqlType(..), fromPersistValueJSON, toPersistValueJSON)
import Database.Persist.Sql (PersistFieldSql(..))

instance PersistField Value where
  toPersistValue = toPersistValueJSON
  fromPersistValue = fromPersistValueJSON

instance PersistFieldSql Value where
  sqlType _ = SqlBlob
```
```haskell
{-# LANGUAGE EmptyDataDecls             #-}
{-# LANGUAGE FlexibleContexts           #-}
{-# LANGUAGE GADTs                      #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE QuasiQuotes                #-}
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE TypeApplications           #-}
{-# LANGUAGE TypeFamilies               #-}

import Control.Monad (void)
import Control.Monad.IO.Class (liftIO)
import Control.Monad.Logger (runNoLoggingT)
import Data.Aeson (Value(String))
import Database.Persist (insert, selectList)
import Database.Persist.Postgresql (withPostgresqlConn)
import Database.Persist.Sql (runMigration, runSqlConn)
import Database.Persist.TH (mkMigrate, mkPersist, persistLowerCase, share, sqlSettings)

import ValueOrphan ()

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Foo
  value Value
|]

main :: IO ()
main = runNoLoggingT $ withPostgresqlConn "postgresql://postgres@localhost/leapyear" $ runSqlConn $ do
  runMigration migrateAll
  void $ insert $ Foo "\""
```

**Comment by parsonsmatt** [comment]
> Value already has an [`IsString` instance](https://www.stackage.org/haddock/lts-14.8/aeson-1.4.5.0/src/Data.Aeson.Types.Internal.html#line-384)?

Oh wow, I did not know that. :|

What error are you observing exactly?

**Comment by brandon-leapyear** [comment]
```
SqlError {sqlState = "22P02", sqlExecStatus = FatalError, sqlErrorMsg = "invalid input syntax for type bytea", sqlErrorDetail = "", sqlErrorHint = ""}
```

**Comment by parsonsmatt** [comment]
This is a bug caused by incompatible `PersistFieldSql` and `PersistField` instances. In `PersistFieldSql`, you say "This is a `SqlBlob`," and the Postgres backend says "Okay, that gets the `bytea` Postgres type." However, you provide it a `PersistText`, which needs a `SqlString` value.

The `persistent-postgresql` backend defines an instance of `postgresql-simple`'s `ToField` class:

```haskell
instance PGTF.ToField P where
    toField (P (PersistText t))        = PGTF.toField t
    toField (P (PersistByteString bs)) = PGTF.toField (PG.Binary bs)
```

The `Binary` there is used to provide an escape for the `bytea` type: https://www.stackage.org/haddock/lts-14.18/postgresql-simple-0.6.2/src/Database.PostgreSQL.Simple.ToField.html#EscapeByteA

I think you'd probably be better off using the instances defined in [`persistent-postgresql`](https://www.stackage.org/haddock/lts-14.18/persistent-postgresql-2.9.1/src/Database.Persist.Postgresql.JSON.html#line-140). That one uses the `PersistDbSpecific` and writes to the Postgres `jsonb` type directly.

(assuming you're using `postgresql`)

**Comment by brandon-leapyear** [comment]
hm ok, well SqlString/PersistText is actually the thing we wanted, so I'll stick with that. Thanks for the feedback, just wanted to double check this wasn't a bug.

**Comment by parsonsmatt** [comment]
Sounds good! Thanks for reporting :) Feel free to post if you have any other questions or issues.

**Comment by brandon-leapyear** [comment]
Is there any existing documentation on PersistFieldSql? Not sure if there's any explicit reference on how/where that typeclass is used by persistent, or how the SqlType matches up with each PersistValue (even though it is fairly straightforward to figure out)

**Comment by parsonsmatt** [comment]
Only the [Haddocks](https://www.stackage.org/haddock/lts-14.18/persistent-2.9.2/Database-Persist-Sql.html#t:PersistFieldSql), IIRC, which are pretty slim.
